### ISSUE TITLE
Address with invalid ERC-55 checksum accepted

### ISSUE THREAD

**Issue by ligi** [ProphetFund/peanut-ui#28]
the current site accepts addresses with invalid ERC-55 checksums. It should check if the address has mixed case encoding - if yes it should check the ERC-55 checksum and reject the address if this fails.
This can reduce the chances funds get stuck.

**Comment by borcherd** [comment]
I suspect you mean the input box when trying to claim manually. I've just pushed a fix to do this. Thanks for noticing!

**Comment by Hugo0** [comment]
thx @borcherd !
