### ISSUE TITLE
(UI Bug) Overflow

### ISSUE THREAD

**Issue by termireum** [ProphetFund/peanut-ui#287]
This bug occurs when you type a very big number in the input field.

How to reproduce?

Press and hold any number on your keyboard.

![bug](https://github.com/peanutprotocol/peanut-ui/assets/72587681/69e76cf1-d710-4a72-9ad4-568af9eb61e7)

**Comment by Hugo0** [comment]
thx for report! paid out a little reward.

**Comment by termireum** [comment]
Thanks for the reward! :)
