### ISSUE TITLE
No mainnets list in modal with chains

### ISSUE THREAD

**Issue by mwx27** [ProphetFund/peanut-ui#67]
After steps described here https://github.com/peanutprotocol/peanut-ui/issues/66 I tried to make some payment link on Ethereum, but unfortunately I could see only testnets in the modal with chains.

Switching chain in Metamask wasn't helpful, as well as switching chain in modal opened by network button (on right top corner of site). Disconnecting wallet and connecting it again also did not help, I had only the choice of testnets.

If I tried to send something, I was asked by metamask to change current chain to chosen testnet.

Only closing site, cleaning cookies ect and open site again helped me to see mainnet chains.

Tested on updated Chrome

**Comment by borcherd** [comment]
Hey there,

Thanks for reaching out and detailing the issue you faced. It sounds like you might've run into a little snag with the testnet toggle in our token selector. When this toggle is set to show testnets, it can sometimes limit the top chain options to just those networks. To see all the chains, including the mainnet ones, you’ll need to open the dropdown (look for the little 'v' on the other side of the toggle) and switch it off.

We’re actually looking to tweak this feature a bit, as it can be a tad confusing, especially for newcomers. Your feedback is super helpful in guiding these updates, so really appreciate you bringing this to our attention.

If you have any more insights or run into anything else, feel free to give us a shout.

**Comment by mwx27** [comment]
Hello,

Of course noticed this little 'v' and tried to open the dropdown. To be honest, I clicked everywhere was possible to make it visible again but no action done on UI side helped to achieve that.

I believe you will manage to tweak it in some smart way!
