### ISSUE TITLE
develop a peanut Safe{Wallet} app

### ISSUE THREAD

**Issue by borcherd** [ProphetFund/peanut-ui#74]
### Description and Objective
Develop a fully functional wallet application that seamlessly incorporates elements from the peanut-ui and integrates the peanut-sdk. The app should be compatible with the Safe protocol, ensuring a robust and secure user experience.

### Acceptance Criteria
- A fully functional wallet app that effectively integrates both peanut-ui elements and peanut-sdk.
- The app must be compatible with and adhere to the Safe core protocol standards.
- Ensure user-friendly interface and smooth functionality.

### Additional Resources
- Peanut SDK Quick Start Guide: [Peanut SDK Documentation](https://docs.peanut.to/integrations/sdk-quick-start)
- Safe Core Protocol: [Safe Protocol Documentation](https://docs.safe.global/safe-core-protocol/safe-core-protocol)
- Quickstart: https://docs.safe.global/safe-apps-sdk/get-started

**Comment by 0xkkonrad** [comment]
will move this to discussions section

**Comment by 0xkkonrad** [comment]
moved to discussion here: https://github.com/orgs/peanutprotocol/discussions/1
