### ISSUE TITLE
USD / Token value input inconsistency

### ISSUE THREAD

**Issue by thegodfatherbeeearth** [ProphetFund/peanut-ui#88]
In random moments Peanut's frontend fails to fetch prices for the tokens selected by the user, which makes the user experience sooo confusing (well, at least for me). 

1. When I initially open Peanut's frontend, I get a page that looks like this and prompts me to specify value in $.
<img width="1440" alt="image" src="https://github.com/peanutprotocol/peanut-ui/assets/63492346/7f96b298-88cd-4aed-ae82-068c543c6e4f">

2. Then I go back and forth between different chains and different tokens and at some random point price query for ETH (or some other token) fails
<img width="388" alt="image" src="https://github.com/peanutprotocol/peanut-ui/assets/63492346/1474f840-e2e3-4d8b-ae4c-fbbb2d158a8e">

3. Which leads to a page like this that prompts me to enter the value in ETH now.
<img width="1440" alt="image" src="https://github.com/peanutprotocol/peanut-ui/assets/63492346/a042a97b-15e4-42fe-acda-f96fb296512f">

For me it really took minutes to notice that it got switched from $ to ETH. I almost thought that there was some amount miscalculation :)

**Comment by borcherd** [comment]
Thanks for reporting, we've noticed that too. It looks like we're getting rate limited by socket.tech, that's why I implemented the fallback to token value. For now, until we have our own api endpoint for token prices, we'll probably leave it as is.

**Comment by thegodfatherbeeearth** [comment]
@borcherd makes sense! Have you thought about making token value the default instead of USD value?

**Comment by borcherd** [comment]
Yes, but since the user wants to know the USD value rather than the token value, we display the USD value by default. Most of the time the api call to socket to fetch the price of the token succeeds, so shouldnt cause an issue in most cases. in the edge case the call fails, we display the token value.

**Comment by thegodfatherbeeearth** [comment]
Alright, thanks!
